language: node_js
node_js:
  - "9.4.0"
cache:
  directories:
    - node_modules/
    - dist/
before_install:
  - npm i -g npm@6.4.1
install:
  - npm install
  - npm install -g codecov
script:
  - npm run build
  - cp ./200.html ./dist/200.html
  - cp ./404.html ./dist/404.html
  - codecov
deploy:
  provider: surge
  project: ./dist/
  skip_cleanup: true
  domain: http://www.kobina.me

