name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          npm install -g npm@6.4.1
          npm install
          npm install -g codecov

      # Step 4: Build the Vue.js app
      - name: Build Project
        run: |
          npm run build

      # Step 5: Prepare SPA Files
      - name: Prepare SPA Files
        run: |
          cp ./200.html ./dist/200.html
          cp ./404.html ./dist/404.html

      # Step 6: Deploy to Surge
      - name: Deploy to Surge
        run: |
          npm install --global surge
          surge ./dist/ http://www.kobina.me
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
